spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/kuitso
#     url: jdbc:h2:tcp://localhost/~/test
#     username: sa
#     password: 1234
#     driver-class-name: org.h2.Driver
    url: jdbc:mysql://kuitso.cpa0kqyuax1o.ap-northeast-2.rds.amazonaws.com:3306/kuitso?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kuitso
    password: kuitso123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true





